name: build
on: [push, pull_request]

jobs:
  gotify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - run: go mod download
      - run: make download-tools
      - run: (cd ui && yarn)
      - run: make build-js
      - run: make embed-static
      - run: |
          export LD_FLAGS="-w -s -X main.Version=0.0.1 -X main.BuildDate=$(date "+%F-%T") -X main.Commit=$(git rev-parse --verify HEAD) -X main.Mode=prod"
          make build
          sudo chown -R $UID build
          make package-zip
          ls -lath build
          make build-docker
          docker image ls
          echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
          docker push --all-tags endoffight/gotify-server
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
